---
- name: Docker install
  block:
    - name: Add universe
      apt_repository: 
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Install addition packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg 
          - lsb-release
          - python3-pip
        update-cache: yes
        cache_valid_time: 86400

    - name: Add Docker key
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg 
        state: present
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add stable repo
      apt_repository: 
        repo: >
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        update-cache: yes
        filename: docker

    - name: Install Docker-ce
      apt:
        name: docker-ce
        update-cache: yes

    - name: Check install and reboor Docker
      service:
        name: docker
        state: restarted
        enabled: true
  become: true

- name: Installing Docker-compose
  block:
  - name: Getting latest version Docker-compose
    uri: 
      url: https://api.github.com/repos/docker/compose/releases/latest
      body_format: json
    register: page
      
  - name: Installing Docker-compose
    get_url:
      url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
      dest: /usr/local/bin/docker-compose
      mode: 0755
  become: true

- name: setting up additional python packages
  block:
  - name: Installing PIP
    pip: 
      name: docker
  
- name: Finishing installation
  block:
  - name: Add user to Docker group
    user:
      name: "{{ansible_user}}"
      groups: docker
      append: true

  - name: Reboot
    reboot:
  become: true
